(() => {
'use strict';
const $ = (s, r = document) => r.querySelector(s), $$ = (s, r = document) => [...r.querySelectorAll(s)];
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
const storage = {get(k){try{return sessionStorage.getItem(k)}catch{return null}},set(k,v){try{sessionStorage.setItem(k,v)}catch{}}};
// Reference timing: 1.5s logo hold, .8s upward curtain.
const intro = $('#intro'); let introTimer, introEnd;
function hideIntro(){if(!intro)return;clearTimeout(introTimer);intro.classList.add('exit');intro.setAttribute('aria-hidden','true');document.body.classList.remove('intro-running');storage.set('mingbao-entered','1');introEnd=setTimeout(()=>{intro.hidden=true},reduced?0:850)}
function playIntro(){if(!intro){location.href='/mingbao-brand-demo/?intro=1';return}clearTimeout(introEnd);intro.hidden=false;intro.classList.remove('exit');intro.removeAttribute('aria-hidden');document.body.classList.add('intro-running');window.scrollTo({top:0,behavior:'instant'});introTimer=setTimeout(hideIntro,1500)}
if(intro){if(reduced||(storage.get('mingbao-entered')&&!new URLSearchParams(location.search).has('intro'))){intro.hidden=true}else{playIntro()}}
$('#skip-intro')?.addEventListener('click',hideIntro);$('#replay-intro')?.addEventListener('click',playIntro);
const header=$('.site-header'),topButton=$('.back-top');let raf=false;
function updateScroll(){header?.classList.toggle('scrolled',scrollY>60);topButton?.classList.toggle('show',scrollY>650);updateStory();raf=false}
addEventListener('scroll',()=>{if(!raf){raf=true;requestAnimationFrame(updateScroll)}},{passive:true});topButton?.addEventListener('click',()=>scrollTo({top:0,behavior:reduced?'instant':'smooth'}));
// Native dialogs provide focus trapping, Escape, and focus restoration.
function openDialog(id){const d=$(id);if(!d)return;d.showModal();if(id==='#video-dialog'){const v=$('video',d);if(!v.src)v.src=v.dataset.src;v.play().catch(()=>{})}if(id==='#search-dialog')requestAnimationFrame(()=>$('#global-search').focus())}
$$('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});$('.close-dialog',d)?.addEventListener('click',()=>d.close());d.addEventListener('close',()=>{$$('video',d).forEach(v=>v.pause())})});
$('.menu-open')?.addEventListener('click',()=>openDialog('#site-menu'));$('.search-open')?.addEventListener('click',()=>openDialog('#search-dialog'));$$('[data-video]').forEach(b=>b.addEventListener('click',()=>openDialog('#video-dialog')));
const sf=$('#search-dialog form');sf?.addEventListener('submit',()=>{sf.action=$('input[name="searchType"]:checked',sf).value});
document.addEventListener('click',e=>{const a=e.target.closest('[data-lightbox]');if(!a)return;e.preventDefault();const src=a.dataset.lightbox||a.getAttribute('href');const d=$('#image-viewer');$('img',d).src=src;$('img',d).alt=$('img',a)?.alt||'茗宝图片';$('a',d).href=src;openDialog('#image-viewer')});
$$('[data-gallery]').forEach((b,i)=>{b.classList.toggle('selected',i===0);b.setAttribute('aria-pressed',i===0?'true':'false');b.addEventListener('click',()=>{const im=$('.detail-media>img');im.src=b.dataset.gallery;$$('[data-gallery]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))})})});
$('.detail-media>img')?.addEventListener('click',e=>{$('#image-viewer img').src=e.target.src;$('#image-viewer a').href=e.target.src;openDialog('#image-viewer')});
// Hero: click + time driven. Offscreen and hidden-tab videos do not consume playback.
const slides=$$('.hero-slide');let slide=0,paused=reduced,heroVisible=true,slideTimer;
function syncVideo(){slides.forEach((el,i)=>{const v=$('video',el);if(i===slide&&!paused&&heroVisible&&!document.hidden){if(v.dataset.src&&!v.getAttribute('src'))v.src=v.dataset.src;v.play().catch(()=>{})}else v.pause()})}
function setSlide(index){slide=(index+slides.length)%slides.length;slides.forEach((el,i)=>{el.classList.toggle('is-active',i===slide);el.inert=i!==slide;el.setAttribute('aria-hidden',String(i!==slide))});$$('[data-go-slide]').forEach((b,i)=>{b.classList.toggle('active',i===slide);b.setAttribute('aria-pressed',String(i===slide))});if($('.slide-line i'))$('.slide-line i').style.width=((slide+1)/3*100)+'%';syncVideo();resetSlideTimer()}
function resetSlideTimer(){clearInterval(slideTimer);if(slides.length&&!paused&&!document.hidden&&heroVisible)slideTimer=setInterval(()=>setSlide(slide+1),9500)}
$$('[data-go-slide]').forEach(b=>b.addEventListener('click',()=>setSlide(Number(b.dataset.goSlide))));
$('#hero-pause')?.addEventListener('click',()=>{paused=!paused;$('#hero-pause').textContent=paused?'▶':'Ⅱ';$('#hero-pause').setAttribute('aria-label',paused?'播放轮播与背景视频':'暂停轮播与背景视频');syncVideo();resetSlideTimer()});
if(slides.length){new IntersectionObserver(([e])=>{heroVisible=e.isIntersecting;syncVideo();resetSlideTimer()},{threshold:.1}).observe($('.hero'));if(reduced){$('#hero-pause').textContent='▶';$('#hero-pause').setAttribute('aria-label','播放轮播与背景视频')}syncVideo();resetSlideTimer()}
addEventListener('visibilitychange',()=>{syncVideo();resetSlideTimer()});
// Once-only scroll entrances, using reference .8s timing and 80% viewport trigger.
const revealTargets=$$('.reveal,.is-interior .category-card,.is-interior .product-card,.is-interior .innovation .inno_col,.is-interior .ab_title,.is-interior .safety_col1 .item');
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('pending');revealObserver.unobserve(e.target)}}),{rootMargin:'0px 0px -8% 0px',threshold:.06});
if(!reduced)revealTargets.forEach(el=>{el.classList.add('reveal');if(el.getBoundingClientRect().top>innerHeight*.9)el.classList.add('pending');revealObserver.observe(el)});
$$('[data-count]').forEach(el=>{const n=Number(el.dataset.count);new IntersectionObserver((entries,observer)=>{if(!entries[0].isIntersecting)return;observer.disconnect();if(reduced)return;const start=performance.now();function tick(now){const f=Math.min(1,(now-start)/1200);el.textContent=Math.round(n*(1-(1-f)**3));if(f<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)},{threshold:.7}).observe(el)});
// Scroll-driven desktop/mobile narrative with click shortcuts to each scroll stage.
const story=$('.tea-story');let storyStep=-1;
const storyContent=[['TEA & NATURE','茶叶与<br>天然植物','提供茶叶、天然植物的初、精、深加工产品和综合解决方案，满足客户定制化需求。','探索产品系列','/mingbao-brand-demo/Product.html#column10012'],['CRAFT & SCIENCE','产品定制<br>创新超越','公司产品以“客户定制”产品为主，这是茗宝服务客户的基础。','查看所有产品','/mingbao-brand-demo/Product.html'],['TASTE & POSSIBILITIES','应用服务<br>成就客户','根据不同客户、不同应用场景等需求，研发出个性化、差异化的产品。','探索应用服务','/mingbao-brand-demo/Product.html#column10013']];
function renderStory(i){if(!story||storyStep===i)return;storyStep=i;story.dataset.step=i;const data=storyContent[i];$('.story-overline').textContent=data[0];$('.story-copy h2').innerHTML=data[1];$('.story-copy>p').textContent=data[2];$('.story-copy>.pill span').textContent=data[3];$('.story-copy>.pill').href=data[4];$('.story-counter').textContent=`0${i+1} — 03`;$$('.story-image').forEach((x,j)=>x.classList.toggle('active',i===j));$$('[data-story]').forEach((x,j)=>{x.classList.toggle('active',i===j);x.setAttribute('aria-pressed',String(i===j))})}
function updateStory(){if(!story||reduced)return;const rect=story.getBoundingClientRect(),range=story.offsetHeight-innerHeight;const p=Math.max(0,Math.min(.999,(-rect.top)/Math.max(1,range)));renderStory(Math.floor(p*3));if(rect.top<innerHeight&&rect.bottom>0){$('.story-ring').style.transform=`rotate(${p*100-20}deg) scaleX(.95)`}}
$$('[data-story]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.story);if(reduced){renderStory(i);return}const top=scrollY+story.getBoundingClientRect().top+(story.offsetHeight-innerHeight)*(i===0?0:(i+.12)/3);scrollTo({top,behavior:'smooth'})}));renderStory(0);updateScroll();
// Product carousel and category tabs use the complete source catalog.
const track=$('.product-track');let catalogPromise;
function productCard(d){const a=document.createElement('a');a.className='product-card';a.href=d.route;const photo=document.createElement('div');photo.className='card-photo';const im=new Image();im.src=d.image;im.alt=d.title;im.loading='lazy';photo.append(im);const content=document.createElement('div');content.className='card-copy';const h=document.createElement('h3');h.textContent=d.title;const desc=document.createElement('p');desc.className='des';desc.textContent=d.summary;const more=document.createElement('span');more.className='more';more.textContent='了解详情 →';content.append(h,desc,more);a.append(photo,content);return a}
if(track){const initial=track.innerHTML;const move=d=>track.scrollBy({left:d*(track.clientWidth*.75),behavior:reduced?'instant':'smooth'});$('[data-carousel-prev]').addEventListener('click',()=>move(-1));$('[data-carousel-next]').addEventListener('click',()=>move(1));track.addEventListener('scroll',()=>{const p=track.scrollLeft/Math.max(1,track.scrollWidth-track.clientWidth);$('.track-progress i').style.width=(35+p*65)+'%'},{passive:true});track.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1)}});let categoryRequest=0;
$$('[data-category]').forEach(b=>b.addEventListener('click',async()=>{const request=++categoryRequest;try{if(b.dataset.category==='全部'){track.innerHTML=initial}else{catalogPromise??=fetch('/mingbao-brand-demo/catalog.json').then(r=>{if(!r.ok)throw Error();return r.json()});const data=await catalogPromise;if(request!==categoryRequest)return;track.replaceChildren(...data[b.dataset.category].map(productCard))}$$('[data-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});track.scrollLeft=0;$('.track-progress i').style.width='35%'}catch{catalogPromise=null}}));
}
// Search: two datasets, real pagination, visible zero/error states.
const path=location.pathname;if(['/mingbao-brand-demo/SearchProducts.html','/mingbao-brand-demo/SearchNews.html'].includes(path)){
const query=new URLSearchParams(location.search),key=query.get('key')||'',requestedPage=Math.max(1,Math.floor(Number(query.get('page'))||1));const input=$('.search-full input');if(input)input.value=key;
Promise.all(['/mingbao-brand-demo/search-data.json','/mingbao-brand-demo/search-news.json'].map(u=>fetch(u).then(r=>{if(!r.ok)throw Error('数据加载失败');return r.json()}))).then(([products,news])=>{const lists=[products,news].map(data=>data.filter(d=>(d.title+' '+d.summary).toLocaleLowerCase().includes(key.trim().toLocaleLowerCase()))),index=path==='/mingbao-brand-demo/SearchNews.html'?1:0,list=lists[index],pages=Math.ceil(list.length/12),page=Math.min(requestedPage,Math.max(1,pages));const tabs=$('#search-tabs');tabs.replaceChildren();['产品服务','茗宝动态'].forEach((name,i)=>{const a=document.createElement('a');a.href=(i?'/mingbao-brand-demo/SearchNews.html':'/mingbao-brand-demo/SearchProducts.html')+'?key='+encodeURIComponent(key);a.textContent=`${name} (${lists[i].length})`;a.classList.toggle('selected',index===i);tabs.append(a)});$('#search-count').textContent=key?`搜索“${key}”，共 ${list.length} 条结果`:`全部${index?'动态':'产品'}，共 ${list.length} 条结果`;const results=$('#search-results');results.replaceChildren(...list.slice((page-1)*12,page*12).map(productCard));if(!list.length){const p=document.createElement('p');p.className='search-empty';p.textContent='没有找到匹配内容，请尝试其他关键词。';results.append(p)}const nav=$('#search-pages');nav.replaceChildren();for(let i=1;i<=pages;i++){const a=document.createElement('a');a.href=path+'?key='+encodeURIComponent(key)+'&page='+i;a.textContent=i;a.classList.toggle('a_cur',i===page);if(i===page)a.setAttribute('aria-current','page');nav.append(a)}document.body.dataset.searchReady='true'}).catch(()=>{$('#search-count').textContent='搜索暂时无法加载，请刷新后重试。';document.body.dataset.searchReady='error'});
}
// Indicate the section currently being read.
const sections=$$('.section-nav a').map(a=>{try{return{a,section:document.getElementById(new URL(a.href).hash.slice(1))}}catch{return null}}).filter(x=>x?.section);

if(sections.length){const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)sections.forEach(({a,section})=>a.classList.toggle('current',section===e.target))},{rootMargin:'-20% 0px -60% 0px',threshold:0});sections.forEach(x=>observer.observe(x.section))}
// Make source contact details actionable without changing the copy.
$$('.contact dd').forEach(dd=>{if(dd.children.length)return;const txt=dd.textContent;const email=txt.match(/[\w.-]+@[\w.-]+\.[a-z]+/i);if(email){dd.replaceChildren(document.createTextNode(txt.slice(0,email.index)));const a=document.createElement('a');a.href='mailto:'+email[0];a.textContent=email[0];dd.append(a)}else if(/^0\d{3}-\d+$/.test(txt.trim())){const a=document.createElement('a');a.href='tel:'+txt.trim().replaceAll('-','');a.textContent=txt;dd.replaceChildren(a)}});
// Page curtain for local navigation. Native modifier, external, hash and download behavior stays intact.
let leaving=false;document.addEventListener('click',e=>{if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||reduced||leaving)return;const a=e.target.closest('a[href]');if(!a||a.target||a.hasAttribute('download')||a.hasAttribute('data-lightbox'))return;const url=new URL(a.href,location.href);if(url.origin!==location.origin||!['http:','https:'].includes(url.protocol)||url.pathname===location.pathname&&url.search===location.search)return;if(url.pathname.startsWith('/mingbao-brand-demo/assets/')||url.pathname.startsWith('/mingbao-brand-demo/media/'))return;e.preventDefault();leaving=true;$('.page-transition').classList.add('active');setTimeout(()=>location.assign(url.href),280)});
addEventListener('pageshow',()=>{leaving=false;$('.page-transition')?.classList.remove('active')});
})();
